### ISSUE TITLE
Not able to make it work

### ISSUE THREAD

**Issue by sibaps80** [Sagargajare/Zerodha-AutoLogin-Api-with-kite#1]
Hi, 
Is this working.I am not able get through.

![image](https://user-images.githubusercontent.com/21038238/133895281-ba2baee6-fc20-4705-b1f5-8be98f692562.png)

Do i need to subscribe for API.I have created an app in kite developers,using the same api key.

**Comment by Sagargajare** [comment]
You need to pass creds in that API. It will log in to Zerodha kite and it will send post request to redirect URI you configured in Zerodha kite dashboard

**Comment by sibaps80** [comment]
Yes in the post request I am sending all the details credentials pin and apikey.But in the login page its not taking my password and authentication failed is coming and pin page is not coming so giving timeout. 

But while manually trying the URL in chrome browser https://kite.trade/connect/login?api_key=XXXXXX&v=3 its working fine

**Comment by sibaps80** [comment]
I changed my password and retried.Its fine now.Not sure what was the issue
